#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генерирует interface/avatars_fighter.gfx: модель самолёта (GenericFighter) для каждой графической культуры.

Движок собирает имя модели юнита как  <графическая культура страны> + <sprite или sprite_override> [+ уровень],
перебирая уровни сверху вниз. Родные самолёты мода (Rost) описаны только как "<культура>Plane3",
поэтому здесь используется отдельное имя  Fighter  (units/plane.txt: sprite_override = Fighter):
актёр "<культура>Fighter" без номера находится при любом уровне страны и не пересекается с Rost.
Нужен актёр у КАЖДОЙ культуры из common/graphicalculturetype.txt (иначе у страны будет запасная пехота).

Меняйте константы ниже и запускайте заново - файл пересоздаётся целиком:
    python gen_plane_actors.py
"""
import os

MODEL = r"gfx\anims\GenericFighter.xac"
IDLE = r"gfx\anims\FighterMove.xsm"              # отдельной анимации покоя нет - самолёт "летит" на месте
MOVE = r"gfx\anims\FighterMove.xsm"
ATTACK = r"gfx\anims\FighterBombAttack.xsm"      # атака по земле; воздушная: gfx\anims\FighterAirAttack.xsm
SCALE = 4.0                                      # размах крыльев ~3.5 -> ~14 на карте (как у самолётов Rost); правьте здесь
SHADOW_NODE = "GericFighter"                     # узел модели (опечатка в самом файле), на нём висит пятно тени; "" - без тени
SPRITE = "Fighter"                               # имя из  sprite_override =  в units/plane.txt

HERE = os.path.dirname(os.path.abspath(__file__))
cultures = [l.strip() for l in open(os.path.join(HERE, "common", "graphicalculturetype.txt"),
                                    encoding="cp1251") if l.strip() and not l.strip().startswith("#")]

out = []
out.append("# Generated by gen_plane_actors.py - edit the script, not this file.")
out.append("# Plane avatar: the GenericFighter model for every graphical culture (actor name = <culture>" + SPRITE + ").")
out.append("")
out.append("objectTypes = {")
for gc in cultures:
    block = [
        "",
        "\tEMFXActorType = {",
        "\t\tname = \"%s%s\"" % (gc, SPRITE),
        "\t\tactorfile = \"%s\"" % MODEL,
        "",
        "\t\tidle   = \"%s\"" % IDLE,
        "\t\tmove   = \"%s\"" % MOVE,
        "\t\tattack = \"%s\"" % ATTACK,
        "\t\tscale = %s" % SCALE,
    ]
    if SHADOW_NODE:
        block += [
            "",
            "\t\tattach = {",
            "\t\t\tname = \"InfantryShadowblob\"",
            "\t\t\tnode = \"%s\"" % SHADOW_NODE,
            "\t\t\tattachId = 2",
            "\t\t}",
        ]
    block.append("\t}")
    out += block
out.append("}")
out.append("")

path = os.path.join(HERE, "interface", "avatars_fighter.gfx")
with open(path, "w", encoding="cp1251", newline="") as f:
    f.write("\r\n".join(out))
print("записано %s: %d актёров (%s)" % (path, len(cultures), SPRITE))
