#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Генерирует interface/avatars_dragoon.gfx: модель драгуна (GermanMotor) для каждой графической культуры.

Движок собирает имя модели юнита как  <графическая культура страны> + <sprite юнита> [+ номер уровня],
поэтому для sprite = Dragoon нужен актёр "<культура>Dragoon" у КАЖДОЙ культуры из
common/graphicalculturetype.txt (иначе у страны без актёра будет запасная GenericInfantry).

Меняйте MODEL / SCALE ниже и запускайте заново - файл пересоздаётся целиком:
    python gen_dragoon_actors.py
"""
import os

MODEL = r"gfx\anims\GermanMotor.xac"
IDLE = r"gfx\anims\GermanMotorIdle.xsm"
MOVE = r"gfx\anims\GermanMotorMoving.xsm"
ATTACK = IDLE                   # отдельной анимации атаки у GermanMotor нет - стоит на месте
SCALE = 1.2                     # длина модели ~10 ед. -> ~12 на карте (как танк); крупнее/мельче - правьте здесь
SPRITE = "Dragoon"              # имя из  sprite =  в units/dragoon.txt

HERE = os.path.dirname(os.path.abspath(__file__))
cultures = [l.strip() for l in open(os.path.join(HERE, "common", "graphicalculturetype.txt"),
                                    encoding="cp1251") if l.strip() and not l.strip().startswith("#")]

out = []
out.append("# Generated by gen_dragoon_actors.py - edit the script, not this file.")
out.append("# Dragoon avatar: the GermanMotor model for every graphical culture (actor name = <culture>" + SPRITE + ").")
out.append("")
out.append("objectTypes = {")
for gc in cultures:
    out += [
        "",
        "\tEMFXActorType = {",
        "\t\tname = \"%s%s\"" % (gc, SPRITE),
        "\t\tactorfile = \"%s\"" % MODEL,
        "\t\tscale = %s" % SCALE,
        "",
        "\t\tanimation = {",
        "\t\t\tname = \"idle\"",
        "\t\t\tfile = \"%s\"" % IDLE,
        "\t\t\tdefaultAnimationTime = 0.0",
        "\t\t}",
        "",
        "\t\tanimation = {",
        "\t\t\tname = \"move\"",
        "\t\t\tfile = \"%s\"" % MOVE,
        "\t\t\tdefaultAnimationTime = -1.0",
        "\t\t}",
        "",
        "\t\tanimation = {",
        "\t\t\tname = \"attack\"",
        "\t\t\tfile = \"%s\"" % ATTACK,
        "\t\t\tdefaultAnimationTime = 0.0",
        "\t\t}",
        "\t}",
    ]
out.append("}")
out.append("")

path = os.path.join(HERE, "interface", "avatars_dragoon.gfx")
with open(path, "w", encoding="cp1251", newline="") as f:
    f.write("\r\n".join(out))
print("записано %s: %d актёров (%s)" % (path, len(cultures), SPRITE))
